# Generated by Django 4.2.23 on 2025-08-04 13:24

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProformaDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vat_rate', models.DecimalField(blank=True, choices=[(Decimal('0.00'), '%0'), (Decimal('1.00'), '%1'), (Decimal('8.00'), '%8'), (Decimal('10.00'), '%10'), (Decimal('18.00'), '%18'), (Decimal('20.00'), '%20')], decimal_places=2, max_digits=5, null=True)),
                ('currency', models.CharField(blank=True, choices=[('TRY', '₺'), ('USD', '$'), ('EUR', '€')], max_length=3, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, help_text='1 {currency} = ? TRY', max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProformaInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('currency', models.CharField(choices=[('TRY', '₺'), ('USD', '$'), ('EUR', '€')], max_length=3)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, help_text='1 {currency} = ? TRY', max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProformaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proforma.proformainvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProformaDraftItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, help_text='1 {currency} = ? TRY', max_digits=10, null=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proforma.proformadraft')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
            options={
                'unique_together': {('draft', 'product')},
            },
        ),
    ]
