# Generated by Django 4.2.23 on 2025-08-04 13:20

import autoslug.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kategori Adı')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, unique_for_date='publish', verbose_name='Link Oluşturucu')),
            ],
            options={
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(blank=True, max_length=15, verbose_name='REF NO')),
                ('barcode', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Sadece rakam giriniz', regex='^\\d+$')], verbose_name='Barkod Numarası')),
                ('name_tr', models.CharField(blank=True, max_length=255, verbose_name='Ürün Adı TR')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='Ürün Adı EN')),
                ('udino', models.CharField(blank=True, max_length=20, verbose_name='UDI Numarası')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Mevcut Stok Adedi')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='ref_no', unique=True, unique_for_date='publish', verbose_name='Link Oluşturucu')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category', verbose_name='Kategori Adı')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['ref_no'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Birim')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, unique_for_date='publish', verbose_name='Link Oluşturucu')),
            ],
            options={
                'verbose_name_plural': 'Birimler',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Depo')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, unique_for_date='publish', verbose_name='Link Oluşturucu')),
            ],
            options={
                'verbose_name_plural': 'Depolar',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Giriş'), ('OUT', 'Çıkış')], max_length=3, verbose_name='Hareket Tipi')),
                ('quantity', models.IntegerField(verbose_name='Adet')),
                ('lot_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lot Numarası')),
                ('movement_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hareket Tarihi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.product', verbose_name='Ürün')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='İşlem Yapan Kullanıcı')),
            ],
            options={
                'verbose_name': 'Stok Hareketi',
                'verbose_name_plural': 'Stok Hareketleri',
                'ordering': ['-movement_date'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.unit', verbose_name='Birim'),
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse', verbose_name='Depo'),
        ),
    ]
