# Generated by Django 4.2.23 on 2025-08-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_stockmovement_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.FloatField(default=0, verbose_name='Mevcut Stok Adedi'),
        ),
    ]
