# Generated by Django 4.2.23 on 2025-08-04 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('lot_number', models.CharField(max_length=100)),
                ('paper', models.CharField(choices=[('Medikal Kraft Kağıt', 'Medikal Kraft Kağıt'), ('Tyvek', 'Tyvek')], max_length=50)),
                ('paper_en', models.CharField(blank=True, max_length=100)),
                ('film', models.CharField(choices=[('CPP+PET', 'CPP+PET'), ('PET+PE', 'PET+PE')], max_length=50)),
                ('film_en', models.CharField(blank=True, max_length=100)),
                ('paper_weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('film_weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('paper_thickness', models.DecimalField(decimal_places=2, max_digits=6)),
                ('film_thickness', models.DecimalField(decimal_places=2, max_digits=6)),
                ('size_check', models.CharField(choices=[('uygun', 'Uygun'), ('uygun_degil', 'Uygun Değil')], max_length=20)),
                ('size_check_en', models.CharField(blank=True, max_length=50)),
                ('seal_strength_left', models.DecimalField(decimal_places=2, max_digits=6)),
                ('seal_strength_right', models.DecimalField(decimal_places=2, max_digits=6)),
                ('seal_strength_top', models.DecimalField(decimal_places=2, max_digits=6)),
                ('leakage_test', models.CharField(choices=[('uygun', 'Uygun'), ('uygun_degil', 'Uygun Değil')], max_length=20)),
                ('leakage_test_en', models.CharField(blank=True, max_length=50)),
                ('peeling_direction', models.CharField(choices=[('uygun', 'Uygun'), ('uygun_degil', 'Uygun Değil')], max_length=20)),
                ('peeling_direction_en', models.CharField(blank=True, max_length=50)),
                ('indicator_1', models.CharField(choices=[('buhar', 'Buhar'), ('eo', 'EO'), ('plazma', 'Plazma')], max_length=10)),
                ('indicator_2', models.CharField(choices=[('buhar', 'Buhar'), ('eo', 'EO'), ('plazma', 'Plazma')], max_length=10)),
                ('indicator_1_en', models.CharField(blank=True, max_length=50)),
                ('indicator_2_en', models.CharField(blank=True, max_length=50)),
                ('indicator_1_color_change', models.CharField(choices=[('yesilimsi siyah', 'Yeşilimsi Siyah'), ('sari', 'Sarı'), ('yesil', 'Yeşil'), ('kahverengi', 'Kahverengi')], max_length=20)),
                ('indicator_1_color_change_en', models.CharField(blank=True, max_length=20)),
                ('indicator_2_color_change', models.CharField(choices=[('yesilimsi siyah', 'Yeşilimsi Siyah'), ('sari', 'Sarı'), ('yesil', 'Yeşil'), ('kahverengi', 'Kahverengi')], max_length=20)),
                ('indicator_2_color_change_en', models.CharField(blank=True, max_length=20)),
                ('report_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
    ]
