# Generated by Django 4.2.23 on 2025-08-12 16:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_alter_product_stock_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(max_length=50, unique=True, verbose_name='Baskı Ref No')),
                ('order_no', models.CharField(editable=False, max_length=20, unique=True)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Toplam Kg')),
                ('kazan_size', models.CharField(max_length=50, verbose_name='Kazan Ölçüsü')),
                ('print_surface', models.CharField(choices=[('ic', 'İç'), ('dis', 'Dış')], max_length=10, verbose_name='Baskı Yüzeyi')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Tarih')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Kullanılacak Kağıt')),
            ],
        ),
        migrations.CreateModel(
            name='PrintingOrderMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('raw_out', 'Hammadde Çıkışı'), ('semi_in', 'Yarı Mamul Girişi'), ('final_in', 'Mamül Girişi')], max_length=20)),
                ('batch_no', models.CharField(max_length=50, verbose_name='Parti No')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='printing.printingorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
    ]
