# Generated by Django 4.2.23 on 2025-08-12 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintingRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(max_length=50, unique=True, verbose_name='Baskı Ref No')),
                ('kazan_size', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Kazan Ölçüsü (cm)')),
            ],
        ),
        migrations.RemoveField(
            model_name='printingorder',
            name='kazan_size',
        ),
        migrations.RemoveField(
            model_name='printingorder',
            name='ref_no',
        ),
        migrations.AddField(
            model_name='printingorder',
            name='ref',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='printing.printingref', verbose_name='Baskı Ref No'),
            preserve_default=False,
        ),
    ]
