# Generated by Django 4.2.23 on 2025-08-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printingref',
            name='total_semi_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Toplam Yarı Mamul KG'),
        ),
        migrations.AlterField(
            model_name='printingorder',
            name='order_no',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='printingorder',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Toplam KG'),
        ),
    ]
