# Generated by Django 4.2.23 on 2025-08-12 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_stock_quantity'),
        ('printing', '0002_printingref_remove_printingorder_kazan_size_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printingorder',
            options={'verbose_name': 'Baskı Siparişi', 'verbose_name_plural': 'Baskı Siparişleri'},
        ),
        migrations.RemoveField(
            model_name='printingorder',
            name='order_no',
        ),
        migrations.RemoveField(
            model_name='printingorder',
            name='print_surface',
        ),
        migrations.RemoveField(
            model_name='printingorder',
            name='ref',
        ),
        migrations.RemoveField(
            model_name='printingorder',
            name='weight_kg',
        ),
        migrations.AddField(
            model_name='printingorder',
            name='ref_no',
            field=models.CharField(default=1, max_length=15, verbose_name='REF NO'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='printingorder',
            name='surface',
            field=models.CharField(choices=[('iç', 'İç'), ('dış', 'Dış')], default=1, max_length=10, verbose_name='Baskı Yüzeyi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='printingorder',
            name='weight',
            field=models.FloatField(default=1, verbose_name='Ağırlık (kg)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='printingorder',
            name='date',
            field=models.DateField(verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='printingorder',
            name='description',
            field=models.TextField(blank=True, default=1, verbose_name='Açıklama'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='printingorder',
            name='paper',
            field=models.ForeignKey(limit_choices_to={'category__name': 'KAĞIT'}, on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Kullanılacak Kağıt'),
        ),
    ]
