# Generated by Django 4.2.23 on 2025-08-13 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_stock_quantity'),
        ('printing', '0002_printingref_total_semi_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printingordermovement',
            name='semi_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='printing.printingref'),
        ),
        migrations.AlterField(
            model_name='printingordermovement',
            name='movement_type',
            field=models.CharField(choices=[('final_in', 'Mamül Girişi'), ('semi_in', 'Yarı Mamul Girişi')], max_length=20),
        ),
        migrations.AlterField(
            model_name='printingordermovement',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
    ]
