# Generated by Django 4.2.23 on 2025-08-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0003_printingordermovement_semi_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printingorder',
            name='status_override',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
