# Generated by Django 4.2.23 on 2025-08-12 20:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_stock_quantity'),
        ('printing', '0003_alter_printingorder_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printingorder',
            options={},
        ),
        migrations.AddField(
            model_name='printingorder',
            name='order_no',
            field=models.CharField(default=1, editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='printingorder',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='printingorder',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='printingorder',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Kullanılacak Kağıt'),
        ),
        migrations.AlterField(
            model_name='printingorder',
            name='ref_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='printing.printingref', verbose_name='Baskı Ref No'),
        ),
        migrations.AlterField(
            model_name='printingorder',
            name='surface',
            field=models.CharField(choices=[('ic', 'İç'), ('dis', 'Dış')], max_length=10, verbose_name='Baskı Yüzeyi'),
        ),
        migrations.AlterField(
            model_name='printingorder',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Toplam Kg'),
        ),
    ]
